-- the first script for migration
create table Wine (
    id bigint generated by default as identity,
    name varchar(255),
    grapes varchar(255),
    country varchar(255),
    region varchar(255),
    year int,
    primary key (id)
);

